#include<stdio.h>
#include<stdlib.h>
int main()
{
    char n[100];
    int phn;
    int id;

    int soap;
    int shampoo;
    int spray;
    int gel;

    int sugar;
    int flour;
    int rice;
    int tea;

    int pepsi;
    int coke;
    int coffee;
    int thumbs_up;

    printf("\t\t---------BILLING SYSTEM---------\n");
    printf("\t\t--------------------------------\n");
    printf("Customer Details\n\n");

    printf("Customer name: ");
    scanf("%s",&n);
    printf("Phone number: ");
    scanf("%d",&phn);
    printf("Customer ID: ");
    scanf("%d",&id);
    printf("\t------------------------------------\n");
    printf("Cosmetics\n\n");
    printf("Soap: ");
    scanf("%d",&soap);
    printf("Shampoo: ");
    scanf("%d",&shampoo);
    printf("Spray: ");
    scanf("%d",&spray);
    printf("Gel: ");
    scanf("%d",&gel);
    printf("\t------------------------------------\n");
    printf("Groceries\n\n");
    printf("Sugar: ");
    scanf("%d",&sugar);
    printf("Flour: ");
    scanf("%d",&flour);
    printf("Rice: ");
    scanf("%d",&rice);
    printf("Tea: ");
    scanf("%d",&tea);
    printf("\t------------------------------------\n");
    printf("Beverages\n\n");
    printf("Pepsi: ");
    scanf("%d",&pepsi);
    printf("Coca Cola: ");
    scanf("%d",&coke);
    printf("Coffee: ");
    scanf("%d",&coffee);
    printf("Thumbs up: ");
    scanf("%d",&thumbs_up);
    printf("\t------------------------------------\n");
    int so;
    int sh;
    int sp;
    int ge;
    int cos;
    so=50*soap;
    sh=150*shampoo;
    sp=100*spray;
    ge=10*gel;
    cos=so+sh+sp+ge;
    printf("Soap: ");
    printf("%d, Rs\n",so);
    printf("Shampoo: ");
    printf("%d Rs\n",sh);
    printf("Spray: ");
    printf("%d Rs\n",sp);
    printf("Gel: ");
    printf("%d Rs\n",ge);
    printf("Total Cosmetics Price: ");
    printf("%d Rs\n",cos);
    printf("\t------------------------------------\n");
    int su;
    int fl;
    int ri;
    int te;
    int gro;
    su=42*sugar;
    fl=35*flour;
    ri=50*rice;
    te=25*tea;
    gro=su+fl+ri+te;
    printf("Sugar: ");
    printf("%d, Rs\n",su);
    printf("Flour: ");
    printf("%d Rs\n",fl);
    printf("Rice: ");
    printf("%d Rs\n",ri);
    printf("Tea: ");
    printf("%d Rs\n",te);
    printf("Total Groceries Price: ");
    printf("%d Rs\n",gro);
    printf("\t------------------------------------\n");
    int pe;
    int co;
    int cof;
    int tu;
    int bev;
    pe=50*pepsi;
    co=95*coke;
    cof=10*coffee;
    tu=40*thumbs_up;
    bev=pe+co+cof+tu;
    printf("Pepsi: ");
    printf("%d, Rs\n",pe);
    printf("Coca Cola: ");
    printf("%d Rs\n",co);
    printf("Coffee: ");
    printf("%d Rs\n",cof);
    printf("Thumbs Up: ");
    printf("%d Rs\n",tu);
    printf("Total Beverages Price: ");
    printf("%d Rs\n",bev);
    printf("\t------------------------------------\n");
    int total=bev+cos+gro;
    printf("Total Amount: ");
    printf("%d Rs\n",total);
    printf("\t------------------------------------\n");
    printf("\t-------------------------------------------------------------------------------\n");
    printf("The Market Point\n\n");

    printf("Product Name                           Quantity                           Price\n\n");
    printf("Soap                                    %d                                %d\n",soap,so);
    printf("Shampoo                                 %d                                %d\n",shampoo,sh);
    printf("Spray                                   %d                                %d\n",spray,sp);
    printf("Gel                                     %d                                %d\n",gel,ge);
    printf("Sugar                                   %d                                %d\n",sugar,su);
    printf("Flour                                   %d                                %d\n",flour,fl);
    printf("Rice                                    %d                                %d\n",rice,ri);
    printf("Tea                                     %d                                %d\n",tea,te);
    printf("Pepsi                                   %d                                %d\n",pepsi,pe);
    printf("Coca Cola                               %d                                %d\n",coke,co);
    printf("Coffe                                   %d                                %d\n",coffee,cof);
    printf("Thumbs Up                               %d                                %d\n",thumbs_up,tu);
    printf("Grocery Total Price: %d Rs\n\n",gro);
    printf("Cosmetics Total Price: %d Rs\n\n",cos);
    printf("Beverages Total Price: %d Rs\n\n",bev);
    printf("Total Price: %d Rs\n\n",total);
    printf("\t THANK YOU VISIT AGAIN");
    printf("\t-------------------------------------------------------------------------------\n");
    system("pause");
    return 0;
}